-- Migration to add physical properties for books
ALTER TABLE books ADD COLUMN IF NOT EXISTS width TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS height TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS pages TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS cover_type TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS flaps TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS interior_paper TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS cover_paper TEXT;
ALTER TABLE books ADD COLUMN IF NOT EXISTS cover_finish TEXT;
