ALTER TABLE quotes ADD COLUMN IF NOT EXISTS quoted_amount_2 NUMERIC DEFAULT 0;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS quoted_amount_3 NUMERIC DEFAULT 0;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS quoted_amount_4 NUMERIC DEFAULT 0;
