ALTER TABLE public.books ADD COLUMN IF NOT EXISTS width TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS height TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS pages INTEGER;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS pages_color TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS sku TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS has_legal_deposit TEXT DEFAULT 'No';
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS legal_deposit_number TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS cover_type TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS flaps TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS flap_width TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS interior_paper TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS cover_paper TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS cover_finish TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS delivery_date DATE;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS contract_status TEXT DEFAULT 'Borrador';
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS contract_date DATE;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS contract_file TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS final_pdf_interior TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS final_pdf_cover TEXT;
ALTER TABLE public.books ADD COLUMN IF NOT EXISTS format TEXT DEFAULT 'Físico';
