ALTER TABLE quotes ADD COLUMN IF NOT EXISTS requested_amount_2 NUMERIC DEFAULT 0;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS requested_amount_3 NUMERIC DEFAULT 0;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS requested_amount_4 NUMERIC DEFAULT 0;
